// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0HLswMmYS4TWJhfXYjJTs_v4Bk6jYU-I',
    appId: '1:1097679044108:web:b2c37b62be386a07f3f829',
    messagingSenderId: '1097679044108',
    projectId: 'netapp-80cbd',
    authDomain: 'netapp-80cbd.firebaseapp.com',
    storageBucket: 'netapp-80cbd.appspot.com',
    measurementId: 'G-80QHPBXW1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABZTvHAR2oN0wNw3bZFkV9ceqIOWjIPvg',
    appId: '1:1097679044108:android:04845bb2969ca1cff3f829',
    messagingSenderId: '1097679044108',
    projectId: 'netapp-80cbd',
    storageBucket: 'netapp-80cbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNKVujYAX3DeUE6DPfggzou7FT3lI-0CU',
    appId: '1:1097679044108:ios:5d321c76f8a243def3f829',
    messagingSenderId: '1097679044108',
    projectId: 'netapp-80cbd',
    storageBucket: 'netapp-80cbd.appspot.com',
    iosClientId: '1097679044108-iojo53cq698u80rrkvuss97be7ngok4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.netapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNKVujYAX3DeUE6DPfggzou7FT3lI-0CU',
    appId: '1:1097679044108:ios:3c2f8d5741091351f3f829',
    messagingSenderId: '1097679044108',
    projectId: 'netapp-80cbd',
    storageBucket: 'netapp-80cbd.appspot.com',
    iosClientId: '1097679044108-9djqmjgevvvpdamsqhbpafis5tmjpph6.apps.googleusercontent.com',
    iosBundleId: 'com.example.netapp.RunnerTests',
  );
}
